### ISSUE TITLE
Template engine to use

### ISSUE THREAD

**Issue by zarak** [zarak/explore-django#3]
There is no template engine specified in the minimalist configuration. Should Jinja be used here, or something else?

**Comment by epogrebnyak** [comment]
A very-very striped down configuratin can live with no template. Template is just another layer for convenience of creating an HTML, but in prinicple it is still some text. So the minimal can live with no template, in my opinion.

**Comment by zarak** [comment]
Yes I think we can introduce it when the need arises.
